# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"z\n\nGenRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x10\n\x08messages\x18\x03 \x03(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05\x12\x0e\n\x06stream\x18\x06 \x01(\x08\"D\n\x0bGenResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x13\n\x0btokens_used\x18\x03 \x01(\x05\x32|\n\x0cModelService\x12\x31\n\x08Generate\x12\x11.model.GenRequest\x1a\x12.model.GenResponse\x12\x39\n\x0eGenerateStream\x12\x11.model.GenRequest\x1a\x12.model.GenResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENREQUEST']._serialized_start=22
  _globals['_GENREQUEST']._serialized_end=144
  _globals['_GENRESPONSE']._serialized_start=146
  _globals['_GENRESPONSE']._serialized_end=214
  _globals['_MODELSERVICE']._serialized_start=216
  _globals['_MODELSERVICE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
