# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import billing_pb2 as billing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in billing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Charge = channel.unary_unary(
                '/billing.BillingService/Charge',
                request_serializer=billing__pb2.BillRequest.SerializeToString,
                response_deserializer=billing__pb2.BillResponse.FromString,
                _registered_method=True)
        self.Reserve = channel.unary_unary(
                '/billing.BillingService/Reserve',
                request_serializer=billing__pb2.ReserveRequest.SerializeToString,
                response_deserializer=billing__pb2.ReserveResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/billing.BillingService/Commit',
                request_serializer=billing__pb2.CommitRequest.SerializeToString,
                response_deserializer=billing__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/billing.BillingService/GetBalance',
                request_serializer=billing__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=billing__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.AdjustBalance = channel.unary_unary(
                '/billing.BillingService/AdjustBalance',
                request_serializer=billing__pb2.AdjustBalanceRequest.SerializeToString,
                response_deserializer=billing__pb2.AdjustBalanceResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Charge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Charge': grpc.unary_unary_rpc_method_handler(
                    servicer.Charge,
                    request_deserializer=billing__pb2.BillRequest.FromString,
                    response_serializer=billing__pb2.BillResponse.SerializeToString,
            ),
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=billing__pb2.ReserveRequest.FromString,
                    response_serializer=billing__pb2.ReserveResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=billing__pb2.CommitRequest.FromString,
                    response_serializer=billing__pb2.CommitResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=billing__pb2.GetBalanceRequest.FromString,
                    response_serializer=billing__pb2.GetBalanceResponse.SerializeToString,
            ),
            'AdjustBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustBalance,
                    request_deserializer=billing__pb2.AdjustBalanceRequest.FromString,
                    response_serializer=billing__pb2.AdjustBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billing.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('billing.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Charge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.BillingService/Charge',
            billing__pb2.BillRequest.SerializeToString,
            billing__pb2.BillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.BillingService/Reserve',
            billing__pb2.ReserveRequest.SerializeToString,
            billing__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.BillingService/Commit',
            billing__pb2.CommitRequest.SerializeToString,
            billing__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.BillingService/GetBalance',
            billing__pb2.GetBalanceRequest.SerializeToString,
            billing__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.BillingService/AdjustBalance',
            billing__pb2.AdjustBalanceRequest.SerializeToString,
            billing__pb2.AdjustBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
